---
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Add Jenkins apt repository key.
  become: yes
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins.io.key"
    state: present
 

- name: Add Jenkins apt repository.
  become: yes
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian binary/'
    state: present

- name: Install Jenkins
  become: yes
  apt:
    name: jenkins
    state: present

#- script: /home/ubuntu/roles/removeScript.sh



#- name: Downloading jenkins ur1
 # get_url:
  #  url: 'https://pkg.jenkins.io/debian binary/'
   # dest: /home/ubuntu/amit
    

