---
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Add Jenkins apt repository key.
  become: yes
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins.io.key"
    state: present
 

- name: Add Jenkins apt repository.
  become: yes
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian binary/'
    state: present

- name: Install Jenkins
  become: yes
  apt:
    name: jenkins
    state: present

- name: Creating a directory called init.groovy.d/
  become: yes
  file:
    path: /var/lib/jenkins/init.groovy.d/
    state: directory
    mode: 0777

- name: copying groovy file
  become: yes
  copy:
    src: /home/ubuntu/ansible/user.groovy
    dest: /var/lib/jenkins/init.groovy.d/
    owner: jenkins
    group: jenkins
    mode: 0777

- name: restarting jenkins service, so that groovy file can load up
  become: yes
  service:
    name: jenkins
    state: restarted

- pause:
    minutes: 1


- name: Install plugin
  jenkins_plugin:
    name: "{{ item }}"
    validate_certs: no
    url_username: amit
    url_password: amit
    url: http://34.208.214.229:8080
    url: http://54.200.141.25:8080
  with_items: 
     - slack
     - git

#- name: Install plugin
 # validate_certs: no
  #jenkins_plugin:
   # validate_certs: no
 #   name: slack
  #  validate_certs: no
   # url_username: amit
    #url_password: amit
    #url: http://54.200.141.25:8080







#- name: Install plugin
 # jenkins_plugin:
  #  name: build-pipeline-plugin






#script: /home/ubuntu/roles/removeScript.sh



#- name: Downloading jenkins ur1
 # get_url:
  #  url: 'https://pkg.jenkins.io/debian binary/'
   # dest: /home/ubuntu/amit
    

